### ISSUE TITLE
TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by zero734kr** [Vendetta-Team/pc-info-example#1]
## 재현 방법
이더넷으로 인터넷 연결 후 프로그램 사용

## 예상되는 정상적인 동작
인터넷 정보를 읽어와 보여주는 것

## 발생한 문제
이더넷으로 인터넷을 접속 후 프로그램을 사용하게 되면 networkInterfaces 메소드에서 Wi-Fi property가 아닌 lo, enp2s0 properties가 출력되어 Wi-Fi를 불러올시 undefined으로 뜨며, 이 undefined에서 1 값을 읽으려 하자 오류 발생 후 모든 정보 출력 안 합니다

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by CistusF** [comment]
#오류가 확인되었습니다.

해당 오류에 대해 인지하였으며

해당부분에 대한 수정을 진행중입니다.

최대한 빠른시일내에 수정하겠으며

해당 오류에 대한 정보는 수정후 전달해드리겠습니다.

**Comment by CistusF** [comment]
@zero734kr 
해당 오류에 대해
```js
for (const nets in networkInterfaces) {
                        netinfo += `<h3>${nets}</h3><hr><h5>주소 : ${networkInterfaces[nets][1].address}<br>넷마스트 : ${networkInterfaces[nets][1].netmask}<br>맥주소 : ${networkInterfaces[nets][1].mac}<br></h5>`
                    }
document.getElementById('netinfo').innerHTML = `${netinfo}`
```
와 같은 업데이트를 진행하였으며
더이상 오류가 없다고 판단되었습니다.

혹시 문제가 생길시 다시 티켓을 열어주시길 바라오며
해당 티켓은 닫도록 하겠습니다.
